#!/bin/bash
node  jd_bean_change.js
node  jd_bean_home.js
node  jd_bean_sign.js
node  jd_blueCoin.js
node  jd_bookshop.js
node  jd_car.js
node  jd_car_exchange.js
node  jd_cash.js
node  jd_club_lottery.js
#node  jd_crazy_joy.js
#node  jd_crazy_joy_coin.js
node  jd_daily_egg.js
node  jd_dreamFactory.js
node  jd_family.js
node  jd_fruit.js
node  jd_get_share_code.js
node  jd_jdfactory.js
node  jd_jdzz.js
node  jd_jxnc.js
node  jd_kd.js
node  jd_live.js
node  jd_lotteryMachine.js
node  jd_moneyTree.js
node  jd_necklace.js
node  jd_nh.js
node  jd_pet.js
#node  jd_petTreasureBox.js
node  jd_pigPet.js
node  jd_plantBean.js
node  jd_rankingList.js
node  jd_redPacket.js
node  jd_shop.js
node  jd_small_home.js
node  jd_speed.js
node  jd_superMarket.js
node  jd_syj.js
node  jd_unbind.js
node  jd_unsubscribe.js
node  jd_bean_change.js

